// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPHnU2mSCcJ5VorRnR7SL_g9cSVU8FAlk',
    appId: '1:999160534648:web:6aaaaea5e8afe44f9b3f8d',
    messagingSenderId: '999160534648',
    projectId: 'taylorapp-3968b',
    authDomain: 'taylorapp-3968b.firebaseapp.com',
    storageBucket: 'taylorapp-3968b.firebasestorage.app',
    measurementId: 'G-GMW520SYHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPeYgwObtWGQFc11KPoILItr3f5EuOp44',
    appId: '1:999160534648:android:ccea29cc9056d5b19b3f8d',
    messagingSenderId: '999160534648',
    projectId: 'taylorapp-3968b',
    storageBucket: 'taylorapp-3968b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgun5Thsz_dgmMeL8AAcACVeStg1T6qWo',
    appId: '1:999160534648:ios:cf52da72b2900dbe9b3f8d',
    messagingSenderId: '999160534648',
    projectId: 'taylorapp-3968b',
    storageBucket: 'taylorapp-3968b.firebasestorage.app',
    iosBundleId: 'com.example.exp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgun5Thsz_dgmMeL8AAcACVeStg1T6qWo',
    appId: '1:999160534648:ios:cf52da72b2900dbe9b3f8d',
    messagingSenderId: '999160534648',
    projectId: 'taylorapp-3968b',
    storageBucket: 'taylorapp-3968b.firebasestorage.app',
    iosBundleId: 'com.example.exp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPHnU2mSCcJ5VorRnR7SL_g9cSVU8FAlk',
    appId: '1:999160534648:web:de76720e2d2d84969b3f8d',
    messagingSenderId: '999160534648',
    projectId: 'taylorapp-3968b',
    authDomain: 'taylorapp-3968b.firebaseapp.com',
    storageBucket: 'taylorapp-3968b.firebasestorage.app',
    measurementId: 'G-PDX3Y7WG8Q',
  );
}
